### ISSUE TITLE
Multiline Input

### ISSUE THREAD

**Issue by Brutuski** [Brutuski/hal2023-cli#1]
Currently only a single line of input in allowed. Pressing `enter` accepts the user input.

However if `shift+enter` would allow the user to enter another line in the query and then pressing `enter` would accept that query, the CLI would be more polished.

**Comment by Brutuski** [comment]
You are absolutely right. `read` doesn't seem to have multiline support the way I was looking for.

Pressing `enter` takes the input immediately, so `shift+enter` makes no difference.

I could go the route of assigning some other key combination to register as end of input, like `ctrl+w` or whatever, and ignoring `enter`. However that would be quite inelegant and really take away from what the CLI should feel like.

**Comment by bionota** [comment]
I don't reckon if you can use trap to get SHIFT+ENTER signal...

However, I just had this idea to get user multiline input. There is only one caveat: on a totally empty line, we will break from the input loop.

This can be adjusted. On pressing CTRL-D and an empty input, read command will exit with 1, so that could be used instead of an empty input to break from the loop..

```
while read -r
do
	case "$REPLY" in
		''|$'\e'*) 	break;; #on empty string or esc
	esac
	PROMPT="${PROMPT}"${PROMPT:+$'\n'}"${REPLY}"
done

printf '%s\n' "$PROMPT"
```

**Comment by bionota** [comment]
Well, I decided to go ahead and implement the following way. The code is just an example:

```
while read -r input
do
	case "$input" in
		*\\)
			PROMPT="${PROMPT}"${PROMPT:+$'\n'}"${input%%\\}"
			;;
		*)
			PROMPT="${PROMPT}"${PROMPT:+$'\n'}"${input}"
			break
			;;
	esac
done
printf '%s\n' "$PROMPT"
```

So, to type in a new line, just end your input with `\`. This is removed and a literal new line is appended (but you could append an encoded newline sign to REPLY).

**Comment by Brutuski** [comment]
Thank you so much for this.
This is really gonna help me brainstorm and implement something.
If you are up to it, feel free to submit a pull request. Otherwise whenever I do push this update, I will tag you for the solution.

On an unrelated note, damn nice [shell wrapper](https://github.com/mountaineerbr/shellChatGPT). 
I might borrow that `.conf` idea. Will link to your repo for the inspiration. Would that be alright with you?
